### ISSUE TITLE
USMF and threaded comments

### ISSUE THREAD

**Issue by sinjax** [lrvick/hyve#1]
Heya,

I was wondering what your take was on USMF and threaded comments. 

I would like to imagine that every comment in a threaded comment system might get its own USMF instance, but in its current form USMF doesn't seem to allow for any notion that a given comment is in reply to another comment. 

Perhaps this is more general, could each USMF object potentially be "in reply" to some other object? This tag could be something like: "in_reply_to" or "replies_to". Of course the question then becomes how that other object would be referred two. Instead of some unique non-service related USMF id perhaps the replies_to entry could be something like:

``` json
"replies_to" : {
  "service": "",
  "id": ""
}
```

This would account for: threaded youtube comments, facebook comments, twitter replies (which are sometimes held in the twitter object), reddit comments being related to reddit posts, reddit comments replying to each other etc.

what do you think?

**Comment by lrvick** [comment]
This is a very reasonable suggestion. USMF needs to have a way to address comments.

I do however think that "service" might be redundant as the first level of USMF defines service.  I feel like it could be safely  assumed that a comment would still be using the same medium. Feel free to share a use case I might be overlooking for that though.

Otherwise looks good. Here is my proposed change, which includes an updated "to_users" block, which between the two should be able to deal with a range of threaded comment use cases.

```
"to_users" {              # Defined if this item is directed at specific user or users
   "0": {                     # Index of user
      "name" : "",                # User Name
      "id" : "",                  # Unique User ID
      "avatar" : "",              # Direct href to avatar for user
      "href" : "",                # Direct href to user profile
   },
},
"replies_to" : {          # Defined if this item is a child in a threaded conversation
   "id"                       # Unique item ID of direct parent of this item
   "root_id"                  # Unique item ID of root item this item is in response to
   "href" : "",               # Direct href to parent item this this item is in response to
   "root_href" : "",          # Direct href to parent item this this item is in response to
},
```

Thoughts?

**Comment by sinjax** [comment]
Hmm I can only think of weird fringe cases. For example [this wordpress plugin](http://wordpress.org/extend/plugins/facebook-comments-for-wordpress/) lets a person put facebook comments on wordpress blog posts. So given that this case is a little weird perhaps it isn't important to encode explicitly

Also I like the explicit encoding of root elements in the "replies_to". This is definitely duplication (as one could traverse the tree and find the root), but practical and useful I think

yeah! good to go I'd say :-)
