### ISSUE TITLE
Licensing?

### ISSUE THREAD

**Issue by clemsos** [lrvick/hyve#2]
Hi there ! Thanks for the awesome job.
I want to use hyve in a research project called  [ Social Brain ](http://sharismlab.com/blog/2012/06/29/social-brain-framework/) where we anatomize collective intelligence through massive SNA of social networks stream. Hyve ans USMF turns up very relevant and useful !  Just wondering about the license you have chosen, as there is no clear indication about that.
Cheers

**Comment by lrvick** [comment]
Apparently I never committed the LICENSE file we use in all the other projects.

Just resolved that. All of our projects are AGPLv3

https://github.com/Tawlk/hyve/blob/develop/LICENSE.md

Will that be usable within the context of your project?

**Comment by clemsos** [comment]
AGPLv3 works just well !

Licensing always gives me headache : http://www.tldrlegal.com/browse
I usually just use the really straightforward Sharing Agreement
http://sharism.org/

Thanks again for the good job !

2012/7/12 Lance R. Vick <
reply@reply.github.com

> Apparently I never committed the LICENSE file we use in all the other
> projects.
> 
> Just resolved that. All of our projects are AGPLv3
> 
> https://github.com/Tawlk/hyve/blob/develop/LICENSE.md
> 
> Will that be usable within the context of your project?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Tawlk/hyve/issues/2#issuecomment-6935792

## 

Clément Renaud

@clemsos
+33 . 0643345655
www.clementrenaud.com
